language: go
os:
  - linux
  - osx
go:
  - 1.9.x
before_install:
  - go get -u --insecure github.com/golang/dep/cmd/dep
  - dep ensure
script:
  - go test -v -cover github.com/gopinath-langote/1build/testing -run .

